version: "3.7"
services:
  juice-shop:
    build: ./juice-shop
    ports:
      - "3000:3000"
  waf:
    image: owasp/modsecurity-crs:4.7.0-nginx-202410090410
    ports:
      - "443:443"
    volumes:
      - "$PWD/nginx-modsecurity-crs/etc/modsecurity:/etc/modsecurity"
      - "$PWD/nginx-modsecurity-crs/etc/modsecurity.d/include.conf:/etc/modsecurity.d/include.conf"
      - "$PWD/nginx-modsecurity-crs/etc/modsecurity.d/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf"
      - "$PWD/nginx-modsecurity-crs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx-modsecurity-crs/etc/nginx/conf.d/default.template:/etc/nginx/conf.d/default.template"
      - "$PWD/nginx-modsecurity-crs/etc/nginx/conf.d/server.crt:/etc/nginx/conf/server.crt"
      - "$PWD/nginx-modsecurity-crs/etc/nginx/conf.d/server.key:/etc/nginx/conf/server.key"
    environment:
      - SERVERNAME=localhost
      - APP_URI="http://172.18.0.2:3000"
    command: /bin/bash -c "envsubst '$$SERVERNAME $$APP_URI' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - juice-shop  
