volumes:
  pgdata:

services:
  juice-shop:
    build: ./juice-shop
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: pr0j3tc1s

  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: projetcis
      POSTGRES_PASSWORD: pr0j3tc1s
      AWS_ACCESS_KEY_ID: ASIAZFNZKMAPFSMCBESZ
      AWS_SECRET_ACCESS_KEY: zU21JNMX+gx2DoWmFVhwZrTKy6LJg1bJ9QSghuGM
      AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEIb//////////wEaCXVzLXdlc3QtMiJHMEUCIGMgcJEQ2b6/POGNis5XM5RswIPE6IkL+iPES75FMj34AiEA3G+JF7sf5l0NzGdihWuv+6LMnouotIyWLZ+7SFe8XNEqugIILxAAGgw2MzAxMzgyMzI4NjIiDLEwgFkrriKOLwj7ICqXAmgzMr1oos4OPmylzlffT/AaFlH4Ul+H2apACLt8w40IBq2wMR3qx2xe1UhroxGd5dtjyFBPZMeCpAJwxRfQT3EWlGo1KeSrglN/vrJuJW4ulU3k00XJIBcW8y+sMBe81V6JeBoYBqNvlDVs5DW0G6df+8dib+EkGmwlZu3DjQcohGXC7X4O9eOGXZnRwVmKMTr3dHbOTEpqcbNHRydZdP5z/bWjyfGD/cNrdk2F0UnTdOf8NUadlw8Gb77qzN4F0DljNw5S8KfZzpIeAaJXesAaS9gi1p4NbFFDyLRXA9HI68xoNcqXlmJdOvUZn3e/PknczLD2pTUPVlXOaKQRlz0/3oMSziwqiJPZ+m3W6Rs1fIonNjnWIDDqm5e6BjqdAcwLwe4HCXLSOp8l3hNQi3Gn0pQ2i9cICe6E7lrAiU3NgtjGPz0ieMMTy6APfPRgLODU4aNTINSDCcq/jYi5iERvkFI9XvnBVMuR/zt1ao2UvYFW+1mc6oL6ONfuugmw0heuISm0G275kiZGzVOpE+kkzCwYzkrMZYU86ryOKfe0qGXxYW3S9paa1J/+EFIhmElCE52VXqIMjv3QoV0=
      AWS_BUCKET_NAME: projetcis
      AWS_BUCKET_REGION: us-east-1
    volumes:
      - pgdata:/var/lib/postgresql/data

  waf:
    image: owasp/modsecurity-crs:4.7.0-nginx-202410090410
    ports:
      - "443:443"
    volumes:
      - "$PWD/nginx-modsecurity-crs/etc/modsecurity:/etc/modsecurity"
      - "$PWD/nginx-modsecurity-crs/etc/modsecurity.d/include.conf:/etc/modsecurity.d/include.conf"
      - "$PWD/nginx-modsecurity-crs/etc/modsecurity.d/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf"
      - "$PWD/nginx-modsecurity-crs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx-modsecurity-crs/etc/nginx/conf.d/default.template:/etc/nginx/conf.d/default.template"
      - "$PWD/nginx-modsecurity-crs/etc/nginx/conf.d/server.crt:/etc/nginx/conf/server.crt"
      - "$PWD/nginx-modsecurity-crs/etc/nginx/conf.d/server.key:/etc/nginx/conf/server.key"
    environment:
      - SERVERNAME=localhost
      - APP_URI="http://172.18.0.2:3000"
    command: /bin/bash -c "envsubst '$$SERVERNAME $$APP_URI' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - juice-shop  
