---
- name: Tear down Kubernetes resources
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Delete the Juice Shop namespace and all resources within it
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        kind: Namespace
        name: "{{ namespace }}"
        wait: true
